# Generated by Django 4.0.5 on 2022-06-14 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customPer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='custom',
            old_name='num',
            new_name='roll',
        ),
    ]
